language: java
jdk:
  - openjdk8
cache:  
  directories:  
   - $HOME/.m2  

before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/setupenvironment.sh
    - git clone https://github.com/SebastianWeberKamp/KAMP4APS.git build/SebastianWeberKamp/KAMP/bundles/KAMP4APS
    - git clone https://github.com/SebastianWeberKamp/KAMP4BP.git build/SebastianWeberKamp/KAMP/bundles/KAMP4BP
    - git clone https://github.com/SebastianWeberKamp/KAMP4HMI.git build/SebastianWeberKamp/KAMP/bundles/KAMP4HMI
    - git clone https://github.com/SebastianWeberKamp/KAMP4IEC.git build/SebastianWeberKamp/KAMP/bundles/KAMP4IEC
    - git clone https://github.com/SebastianWeberKamp/KAMP4IS.git build/SebastianWeberKamp/KAMP/bundles/KAMP4IS

install: true

script: mvn clean verify